USE DATABASE MEETUP_DB;
USE SCHEMA PROCESSED;

-- 1. Crear la conexión directa y segura hacia tu bucket usando tus llaves
CREATE OR REPLACE STAGE MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE
  URL = 's3://meetup-processed-fforero/'
  CREDENTIALS = (
    AWS_KEY_ID = 'xxxxxxxxxxxxxxxx' 
    AWS_SECRET_KEY = 'xxxxxxxxxxxxxxxxxxxxxx'
  );

-- 2. Transfiere la tabla procesada por Airflow a tu AWS S3
COPY INTO @MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE/pipeline_output_events
FROM MEETUP_DB.PROCESSED.EVENTS_ANALYTICS
FILE_FORMAT = (FORMAT_NAME = 'MEETUP_DB.RAW.csv_meetup_format')
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE/pipeline_output_gropus
FROM MEETUP_DB.PROCESSED.DIM_GROUPS
FILE_FORMAT = (FORMAT_NAME = 'MEETUP_DB.RAW.csv_meetup_format')
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE/pipeline_output_members
FROM MEETUP_DB.PROCESSED.DIM_MEMBERS
FILE_FORMAT = (FORMAT_NAME = 'MEETUP_DB.RAW.csv_meetup_format')
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE/pipeline_output_membership_engagement
FROM MEETUP_DB.PROCESSED.FACT_MEMBERSHIP_ENGAGEMENT
FILE_FORMAT = (FORMAT_NAME = 'MEETUP_DB.RAW.csv_meetup_format')
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE/pipeline_output_membership_dim_brigde
FROM MEETUP_DB.PROCESSED.DIM_TOPICS_BRIDGE 
FILE_FORMAT = (FORMAT_NAME = 'MEETUP_DB.RAW.csv_meetup_format')
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE/pipeline_output_membership_AGG_VENUE_GEOMARKETING
FROM MEETUP_DB.PROCESSED.AGG_VENUE_GEOMARKETING 
FILE_FORMAT = (FORMAT_NAME = 'MEETUP_DB.RAW.csv_meetup_format')
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE/pipeline_output_membership_AGG_VENUE_GEOMARKETING
FROM MEETUP_DB.PROCESSED.AGG_VENUE_GEOMARKETING 
FILE_FORMAT = (FORMAT_NAME = 'MEETUP_DB.RAW.csv_meetup_format')
HEADER = TRUE
OVERWRITE = TRUE;

-- 3. Listar el contenido para verificar el éxito de la transferencia
LIST @MEETUP_DB.PROCESSED.AWS_S3_FINAL_STAGE;
