USE DATABASE MEETUP_DB;
USE SCHEMA RAW;
-- 1. Asegurar la configuración del formato de archivo para leer GZIP
CREATE OR REPLACE FILE FORMAT csv_meetup_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  COMPRESSION = 'GZIP'
  ENCODING = 'ISO88591' -- <- Esto arregla los caracteres inválidos automáticamente
  NULL_IF = ('NULL', 'null', '', 'NA');


COPY INTO CATEGORIES_RAW FROM @MEETUP_STAGE/categories.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR ='CONTINUE' FORCE=TRUE;
COPY INTO CITIES_RAW FROM @MEETUP_STAGE/cities.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR = 'CONTINUE' FORCE=TRUE;
COPY INTO EVENTS_RAW FROM @MEETUP_STAGE/events.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR = 'CONTINUE' FORCE=TRUE;
COPY INTO GROUPS_RAW FROM @MEETUP_STAGE/groups.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR = 'CONTINUE' FORCE=TRUE;
COPY INTO GROUPS_TOPICS_RAW FROM @MEETUP_STAGE/groups_topics.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR = 'CONTINUE' FORCE=TRUE;
COPY INTO MEMBERS_RAW FROM @MEETUP_STAGE/members.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR = 'CONTINUE' FORCE=TRUE;
COPY INTO MEMBERS_TOPICS_RAW FROM @MEETUP_STAGE/members_topics.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR = 'CONTINUE' FORCE=TRUE;
COPY INTO TOPICS_RAW FROM @MEETUP_STAGE/topics.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR = 'CONTINUE' FORCE=TRUE;
COPY INTO VENUES_RAW FROM @MEETUP_STAGE/venues.csv.gz FILE_FORMAT = (FORMAT_NAME = 'csv_meetup_format') ON_ERROR = 'CONTINUE' FORCE=TRUE;


     