SELECT DISTINCT 'EVENTS_ANALYTICS' AS TABLA, processed_at 
FROM MEETUP_DB.PROCESSED.EVENTS_ANALYTICS 
UNION
SELECT DISTINCT 'DIM_GROUPS' AS TABLA, processed_at 
FROM MEETUP_DB.PROCESSED.DIM_GROUPS
UNION
SELECT DISTINCT 'DIM_MEMBERS' AS TABLA, processed_at 
FROM MEETUP_DB.PROCESSED.DIM_MEMBERS
UNION
SELECT DISTINCT 'FACT_MEMBERSHIP_ENGAGEMENT' AS TABLA, processed_at 
FROM MEETUP_DB.PROCESSED.FACT_MEMBERSHIP_ENGAGEMENT
UNION
SELECT DISTINCT 'DIM_TOPICS_BRIDGE' AS TABLA, processed_at 
FROM MEETUP_DB.PROCESSED.DIM_TOPICS_BRIDGE
UNION
SELECT DISTINCT 'AGG_VENUE_GEOMARKETING' AS TABLA, processed_at 
FROM MEETUP_DB.PROCESSED.AGG_VENUE_GEOMARKETING
ORDER BY processed_at DESC;




